# Generated by Django 5.1.11 on 2025-11-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_account_medsos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='account_medsos',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Account Medsos'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_source',
            field=models.CharField(blank=True, choices=[('website', 'Website'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('referral', 'Referral'), ('fb_ads', 'FB Ads'), ('teknusa', 'Teknusa'), ('Self', 'Self'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
