# Generated by Django 5.1.11 on 2026-01-12 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_alter_lead_account_medsos_alter_lead_lead_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_source',
            field=models.CharField(blank=True, choices=[('website', 'Website'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('referral', 'Referral'), ('fb_ads', 'FB Ads'), ('teknusa', 'Teknusa'), ('elf', 'Self'), ('threads', 'Threads'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
