# Generated by Django 5.1.11 on 2026-08-16 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_entity_delete_teamexpert'),
        ('leads', '0006_alter_lead_lead_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='entity.entity'),
        ),
    ]
