# Generated by Django 5.1.11 on 2026-08-16 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_entity_delete_teamexpert'),
        ('ledger', '0013_dimensions_and_journalitem_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='entity.entity'),
        ),
        migrations.AddField(
            model_name='closingperiod',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closing_periods', to='entity.entity'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='entity.entity'),
        ),
        migrations.AlterField(
            model_name='closingperiod',
            name='period',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterUniqueTogether(
            name='closingperiod',
            unique_together={('period', 'entity')},
        ),
    ]
