# Generated by Django 5.1.11 on 2026-08-16 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['position', 'id']},
        ),
        migrations.AlterModelOptions(
            name='taskcomment',
            options={'ordering': ['-created_at']},
        ),
    ]
