# Generated by Django 5.1.11 on 2025-12-05 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_media', '0032_alter_channel_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Akun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Biaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FunnelStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Nilai Biaya'),
        ),
        migrations.AlterField(
            model_name='market',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='akun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_media.akun'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='kategori_biaya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_media.biaya'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_media.digitalchannel'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='funnel_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_media.funnelstage'),
        ),
    ]
