# Generated by Django 5.1.11 on 2025-12-05 06:00

from django.db import migrations, models


def fix_foreign_key_constraints(apps, schema_editor):
    """
    Fix foreign key constraint issues by setting null for invalid references
    """
    Channel = apps.get_model('post_media', 'Channel')
    
    # Update channels with invalid akun_id to null
    Channel.objects.filter(akun_id__isnull=False).exclude(akun_id__in=models.Subquery(
        apps.get_model('post_media', 'Akun').objects.values('id')
    )).update(akun_id=None)
    
    # Update channels with invalid for_market_id to null
    Channel.objects.filter(for_market_id__isnull=False).exclude(for_market_id__in=models.Subquery(
        apps.get_model('post_media', 'Market').objects.values('id')
    )).update(for_market_id=None)
    
    # Update channels with invalid channel_id to null
    Channel.objects.filter(channel_id__isnull=False).exclude(channel_id__in=models.Subquery(
        apps.get_model('post_media', 'DigitalChannel').objects.values('id')
    )).update(channel_id=None)
    
    # Update channels with invalid funnel_stage_id to null
    Channel.objects.filter(funnel_stage_id__isnull=False).exclude(funnel_stage_id__in=models.Subquery(
        apps.get_model('post_media', 'FunnelStage').objects.values('id')
    )).update(funnel_stage_id=None)
    
    # Update channels with invalid kategori_biaya_id to null
    Channel.objects.filter(kategori_biaya_id__isnull=False).exclude(kategori_biaya_id__in=models.Subquery(
        apps.get_model('post_media', 'Biaya').objects.values('id')
    )).update(kategori_biaya_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('post_media', '0033_akun_biaya_digitalchannel_funnelstage_channel_amount_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_foreign_key_constraints, migrations.RunPython.noop),
    ]
