# Generated by Django 5.1.11 on 2025-12-05 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_media', '0034_fix_foreign_key_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='akun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post_media.akun'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post_media.digitalchannel'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='for_market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post_media.market'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='funnel_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post_media.funnelstage'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='kategori_biaya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post_media.biaya'),
        ),
    ]
