# Generated by Django 5.1.11 on 2025-12-05 06:05

from django.db import migrations


def create_initial_data(apps, schema_editor):
    """
    Create initial data for foreign key models
    """
    Akun = apps.get_model('post_media', 'Akun')
    Market = apps.get_model('post_media', 'Market')
    DigitalChannel = apps.get_model('post_media', 'DigitalChannel')
    FunnelStage = apps.get_model('post_media', 'FunnelStage')
    Biaya = apps.get_model('post_media', 'Biaya')
    
    # Create default Akun instances
    akun_data = [
        {'name': 'Instagram Business', 'description': 'Instagram Business account'},
        {'name': 'LinkedIn Company', 'description': 'LinkedIn Company page'},
        {'name': 'TikTok Business', 'description': 'TikTok Business account'},
        {'name': 'Blog/Website', 'description': 'Blog or Website platform'},
    ]
    for data in akun_data:
        Akun.objects.get_or_create(name=data['name'], defaults=data)
    
    # Create default DigitalChannel instances
    channel_data = [
        {'name': 'Instagram', 'description': 'Instagram platform'},
        {'name': 'LinkedIn', 'description': 'LinkedIn platform'},
        {'name': 'TikTok', 'description': 'TikTok platform'},
        {'name': 'Blog', 'description': 'Blog/Website platform'},
    ]
    for data in channel_data:
        DigitalChannel.objects.get_or_create(name=data['name'], defaults=data)
    
    # Create default FunnelStage instances
    funnel_data = [
        {'name': 'Awareness', 'description': 'Top of funnel - awareness stage'},
        {'name': 'Consideration', 'description': 'Middle of funnel - consideration stage'},
        {'name': 'Conversion', 'description': 'Bottom of funnel - conversion stage'},
        {'name': 'Retention', 'description': 'Post-purchase - retention stage'},
    ]
    for data in funnel_data:
        FunnelStage.objects.get_or_create(name=data['name'], defaults=data)
    
    # Create default Biaya instances
    biaya_data = [
        {'name': 'Iklan Berbayar', 'description': 'Paid advertising costs'},
        {'name': 'Produk Konten', 'description': 'Content production costs'},
        {'name': 'Tools & Software', 'description': 'Software and tools costs'},
        {'name': 'Lainnya', 'description': 'Other costs'},
    ]
    for data in biaya_data:
        Biaya.objects.get_or_create(name=data['name'], defaults=data)


class Migration(migrations.Migration):

    dependencies = [
        ('post_media', '0035_make_foreign_keys_nullable'),
    ]

    operations = [
        migrations.RunPython(create_initial_data, migrations.RunPython.noop),
    ]
